"""removed some fields

Revision ID: 06df8afc2af6
Revises: bfb9896f29ce
Create Date: 2026-02-17 22:21:37.832526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06df8afc2af6'
down_revision: Union[str, Sequence[str], None] = 'bfb9896f29ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('application', 'how_long_work')
    op.drop_column('application', 'ever_recenptionist')
    op.drop_column('application', 'why_work_with_us')
    op.drop_column('application', 'expected_salary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('expected_salary', sa.VARCHAR(), nullable=True))
    op.add_column('application', sa.Column('why_work_with_us', sa.VARCHAR(), nullable=True))
    op.add_column('application', sa.Column('ever_recenptionist', sa.VARCHAR(), nullable=True))
    op.add_column('application', sa.Column('how_long_work', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
