"""Added new fields to the appliaction mode

Revision ID: 3a0b3231470c
Revises: 58c4b8ac9546
Create Date: 2026-02-03 13:14:41.174461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a0b3231470c'
down_revision: Union[str, Sequence[str], None] = '58c4b8ac9546'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('additional_courses', sa.String(), nullable=True))
    op.add_column('application', sa.Column('additional_course_subject', sa.String(), nullable=True))
    op.add_column('application', sa.Column('marriage_status', sa.String(), nullable=True))
    op.add_column('application', sa.Column('if_children', sa.String(), nullable=True))
    op.add_column('application', sa.Column('how_long_work', sa.String(), nullable=True))
    op.add_column('application', sa.Column('why_work_with_us', sa.String(), nullable=True))
    op.add_column('application', sa.Column('ever_recenptionist', sa.String(), nullable=True))
    op.add_column('application', sa.Column('expected_salary', sa.String(), nullable=True))
    op.create_index(op.f('ix_application_if_children'), 'application', ['if_children'], unique=False)
    op.create_index(op.f('ix_application_marriage_status'), 'application', ['marriage_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_marriage_status'), table_name='application')
    op.drop_index(op.f('ix_application_if_children'), table_name='application')
    op.drop_column('application', 'expected_salary')
    op.drop_column('application', 'ever_recenptionist')
    op.drop_column('application', 'why_work_with_us')
    op.drop_column('application', 'how_long_work')
    op.drop_column('application', 'if_children')
    op.drop_column('application', 'marriage_status')
    op.drop_column('application', 'additional_course_subject')
    op.drop_column('application', 'additional_courses')
    # ### end Alembic commands ###
