"""application model fixed

Revision ID: bfb9896f29ce
Revises: 8a1bcbce9730
Create Date: 2026-02-17 00:54:22.782531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb9896f29ce'
down_revision: Union[str, Sequence[str], None] = '8a1bcbce9730'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("application") as batch_op:
        batch_op.alter_column("first_name", nullable=True)


    with op.batch_alter_table("application") as batch_op:
        batch_op.alter_column(
            "last_name",
            existing_type=sa.VARCHAR(),
            nullable=True
        )

    with op.batch_alter_table("application") as batch_op:
        batch_op.alter_column(
            "birth_date",
            existing_type=sa.VARCHAR(),
            nullable=True
        )

    with op.batch_alter_table("application") as batch_op:
        batch_op.alter_column(
            "gender",
            existing_type=sa.VARCHAR(),
            nullable=True
        )

    with op.batch_alter_table("application") as batch_op:
        batch_op.alter_column(
            "address",
            existing_type=sa.VARCHAR(),
            nullable=True
        )
    with op.batch_alter_table("application") as batch_op:
        batch_op.alter_column(
            "phone_number",
            existing_type=sa.VARCHAR(),
            nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('application', 'phone_number',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('application', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('application', 'gender',
               existing_type=sa.VARCHAR(length=6),
               nullable=False)
    op.alter_column('application', 'birth_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('application', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('application', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
